name: moneycart
description: "A Finance app by Moneycart Finsolv Pvt. Ltd."

version: 1.1.0+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  intl: ^0.19.0
  firebase_storage: ^11.7.7
  image_picker: ^1.1.2
  firebase_auth: ^4.20.0
  flutter_svg: ^2.0.10+1
  flutter_share: ^2.0.0
  form_validator: ^2.1.1
  firebase_messaging: ^14.9.4
  flutter_native_splash: ^2.4.1 
  get: ^4.6.6
  flutter_otp_text_field: ^1.1.3+2
  url_launcher: ^6.3.0
  firebase_app_check: ^0.2.2+7
  flutter_holo_date_picker: ^1.1.3
  firebase_remote_config: ^4.4.7
  in_app_update: ^4.2.3
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  pinput: ^5.0.0
  smart_auth: ^2.0.0
  cached_network_image: ^3.3.1
  flutter_local_notifications: ^17.2.1+2
  awesome_snackbar_content: ^0.1.3
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  http: ^1.2.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#ffffff"  # Background color for splash screen
  image: assets/images/moneycart_icon.png  # Splash screen image

  android_12:
    icon_background_color: "#ffffff"  # Background color for icon in Android 12+
    image: assets/images/moneycart_icon.png  # Image for Android 12+ splash screen

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/
    - assets/fonts/

flutter_launcher_icons:
  android: true
  image_path: "assets/images/moneycart_logo.png"
  android_name: "ic_launcher"
  ios_name: "AppIcon"